version: '3.8'

services:
  app-db:
    image: postgres:15
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qdele
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - app-db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_database
    ports:
      - "5433:5432"
    networks:
      - dev-network
    volumes:
      - test-db-data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  dev-network:
    driver: bridge

volumes:
  app-db-data:
  test-db-data:
